#!/bin/bash
case "$1" in
    install)
        if [ -e /usr/bin/pip ]; then
            echo "pip is already installed"
        else
            echo "Installing pip"
            /usr/bin/easy_install pip
        fi
        if [ -e /usr/bin/virtualenv ]; then
            echo "virtualenv is already installed"
        else
            echo "Installing virtualenv"
            /usr/bin/env pip install virtualenv
        fi
        if [ -d /var/lib/$DPKG_MAINTSCRIPT_PACKAGE ]; then
            echo "Project directory already exists"
        else
            echo "Creating project directory"
            /usr/bin/env virtualenv /var/lib/$DPKG_MAINTSCRIPT_PACKAGE
        fi
    ;;
esac
